name: create-script
version: 0.1.0.0
github: "DerekMaffett/create-script"
license: BSD3
author: "Derek Maffett"
maintainer: "derekgmaffett@gmail.com"
copyright: "GNU GPLv3"

extra-source-files:
    - README.md
    - ChangeLog.md

description: Script

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - unordered-containers
    - process
    - directory
    - yaml

executables:
    create-script:
        main: Main.hs
        source-dirs:
            - .
            - ../utils/src
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - RecordWildCards
    - NamedFieldPuns
    - DuplicateRecordFields
    - DeriveGeneric
    - DeriveAnyClass
