name: setup
version: 0.1.0.0
github: "DerekMaffett/setup"
license: BSD3
author: "Derek Maffett"
maintainer: "deregmaffett@gmail.com"
copyright: "Derek Maffett"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/setup#readme>

dependencies:
    - base >= 4.7 && < 5
    - process
    - optparse-applicative
    - directory
    - parsec
    - hslogger
    - mtl
    - safe
    - unordered-containers
    - hspec

library:
    source-dirs: src

default-extensions:
    - OverloadedStrings
    - NamedFieldPuns
    - DuplicateRecordFields

executables:
    setup:
        main: Main.hs
        source-dirs: .
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
            - -Wall
        dependencies:
            - setup
tests:
    setup-test:
        main: Spec.hs
        source-dirs: spec
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - setup
