name:                setup
version:             0.1.0.0
github:              "githubuser/setup"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/setup#readme>

dependencies:
- base >= 4.7 && < 5
- process
- optparse-applicative
- directory
- parsec
- hslogger
- mtl

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - NamedFieldPuns
  - DuplicateRecordFields

executables:
  setup:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - setup
