name: dotfiles
windows:
    - dotfiles:
          layout: main-vertical
          root: ~/dotfiles
          panes:
              - vim
              - null
    - scripts:
          layout: main-vertical
          root: ~/dotfiles/scripts
          panes:
              - vim
              - stack install --file-watch scripts
              - null
