name: open-source
windows:
- river:
    layout: main-vertical
    root: ~/projects/river
    panes:
    - vim
    - watch-dev
    - null
- river-bitbucket:
    layout: main-vertical
    root: ~/projects/river-bitbucket-test
    panes:
    - vim
    - null
- river-github:
    layout: main-vertical
    root: ~/projects/river-github-test
    panes:
    - vim
    - null
- react-elm:
    layout: main-vertical
    root: ~/projects/react-elm
    panes:
    - vim
    - npm run start
    - null
- todo-app:
    layout: main-vertical
    root: ~/projects/todo-app
    panes:
    - vim
    - pscid -I src
    - parcel src/index.html
- haskell-presentation:
    layout: main-vertical
    root: ~/projects/haskell-presentation
    panes:
    - vim
    - null
    - null
