name: copy
version: 0.1.0.0
github: "DerekMaffett/copy"
license: BSD3
author: "Derek Maffett"
maintainer: "derekgmaffett@gmail.com"
copyright: "GNU GPLv3"

extra-source-files:
    - README.md
    - ChangeLog.md

description: Script

dependencies:
    - base >= 4.7 && < 5
    - process

library:
    source-dirs: .

executables:
    copy:
        main: Main.hs
        source-dirs: .
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - copy
