# /Users/derekmaffett/dotfiles/src/configs/tmuxinator/open-source.yml

name: open-source
root: ~/projects
windows:
    - river:
          layout: main-vertical
          root: ~/projects/river
          panes:
              - vim
              - stack install --file-watch --fast --local-bin-path ./bin
              -  #Shell
    - react-elm:
          layout: main-vertical
          root: ~/projects/react-elm
          panes:
              - vim
              - js-compiler:
                    - git co master
                    - git pull
                    - npm run start
              -  #SHELL
