name: ssh-init
version: 0.1.0.0
github: "DerekMaffett/ssh-init"
license: BSD3
author: "Derek Maffett"
maintainer: "derekgmaffett@gmail.com"
copyright: "GNU GPLv3"

extra-source-files:
    - README.md
    - ChangeLog.md

description: Script

dependencies:
    - base >= 4.7 && < 5
    - aeson
    - process
    - directory
    - text

library:
    source-dirs: .

executables:
    ssh-init:
        main: Main.hs
        source-dirs: .
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts=-N
        dependencies:
            - ssh-init

default-extensions:
    - OverloadedStrings
    - LambdaCase
    - RecordWildCards
    - NamedFieldPuns
    - DuplicateRecordFields
    - DeriveGeneric
    - DeriveAnyClass
